### ISSUE TITLE
Fetch all fields

### ISSUE THREAD

**Issue by fsauter** [dbrekalo/json-api-normalize#1]
Hiho,

thanks for your work!

Just wondering if it would be possible to offer a method that fetches all fields and relations by default?

Something like: `normalize(articleJsonApiData).getAll();`

Is there a reason why you only implemented get only via specific field names?

Cheers Florian

**Comment by dbrekalo** [comment]
Circular references. If you have category entity for example - one of them could have a circular relation to itself (parent category). It is impossibe to flatten this kind of data (category.parent.parent.parent...).

**Comment by Kelin2025** [comment]
@dbrekalo but how `.getAll` differs from transfering all fields manually?

**Comment by stephandesouza** [comment]
@dbrekalo 
The point here is if we could achieve something like this:

    normalize(articleJsonApiData).get([
        'id',
        'title',
        'body',
        'author.*',
        'author.boss.*',
        'tags.*',
    ]);

    // will return
    // {
    //     id: '1',
    //     title: 'JSON API paints my bikeshed!',
    //     body: 'The shortest article. Ever.',
    //     author: {
    //         id: '42',
    //         firstName: 'John',
    //         lastName: 'Doe',
    //         boss: {
    //             firstName: 'John',
    //             lastName: 'Doe'
    //         }
    //     },
    //     tags: [{
    //         id: '1',
    //         name: 'tag 1'
    //     }, {
    //         id: '2',
    //         name: 'tag 2'
    //     }]
    // };
